<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-03 at 09:46:17.
 */
class DigitoolUrlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var DigitoolUrl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DigitoolUrl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
